version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/sgcc_database
      SPRING_RABBITMQ_HOST: rabbitmq

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    command: ["mongod", "--noauth"]  # Desativa a autenticação e permite acesso sem senha

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
